export const JOBS_LIST_REQUEST = "JOBS_LIST_REQUEST";
export const JOBS_LIST_SUCCESS = "JOBS_LIST_SUCCESS";
export const JOBS_LIST_FAIL = "JOBS_LIST_FAIL";

export const INVITED_JOBS_LIST_REQUEST = "INVITED_JOBS_LIST_REQUEST";
export const INVITED_JOBS_LIST_SUCCESS = "INVITED_JOBS_LIST_SUCCESS";
export const INVITED_JOBS_LIST_FAIL = "INVITED_JOBS_LIST_FAIL";
