exports.jobs = [
    {
        id: 1,
        date: new Date('June 24, 2021'),
        startTime: new Date('June 24, 2021 16:30:00'),
        endTime:new Date('June 24, 2021 19:30:00'),
        type: "Intensive Care General",
        salaryPerHour: 40.25,
        place:"A Nice Hospital",
        rating: 3,
        address: "10 Nice Street",
        zipCode: 2000,
        state: "NSW",
        city: "Sydney",
        invitationStatus: true,
        applied: false
    },
    {
        id: 2,
        date: new Date('June 23, 2021'),
        startTime: new Date('June 23, 2021 18:30:00'),
        endTime:new Date('June 23, 2021 19:00:00'),
        type: "Intensive Care General",
        salaryPerHour: 40.25,
        place:"A Nice Hospital",
        rating: 4.5,
        address: "10 Nice Street",
        zipCode: 2000,
        state: "NSW",
        city: "Sydney",
        invitationStatus: false,
        applied: false
    },
    {
        id: 3,
        date: new Date('June 22, 2021'),
        startTime: new Date('June 22, 2021 19:30:00'),
        endTime:new Date('June 22, 2021 20:30:00'),
        type: "Intensive Care General",
        salaryPerHour: 40.25,
        place:"A Nice Hospital",
        rating: 3.5,
        address: "10 Nice Street",
        zipCode: 2000,
        state: "NSW",
        city: "Sydney",
        invitationStatus: false,
        applied: false
    },
    {
        id: 4,
        date: new Date('June 21, 2021'),
        startTime: new Date('June 21, 2021 13:30:00'),
        endTime:new Date('June 21, 2021 16:00:00'),
        type: "Intensive Care General",
        salaryPerHour: 40.25,
        place:"A Nice Hospital",
        rating: 3.5,
        address: "10 Nice Street",
        zipCode: 2000,
        state: "NSW",
        city: "Sydney",
        invitationStatus: false,
        applied: false
    },
    {
        id: 5,
        date: new Date('June 24, 2021'),
        startTime: new Date('June 24, 2021 11:30:00'),
        endTime:new Date('June 24, 2021 16:0:00'),
        type: "Intensive Care General",
        salaryPerHour: 40.25,
        place:"A Nice Hospital",
        rating: 4.5,
        address: "10 Nice Street",
        zipCode: 2000,
        state: "NSW",
        city: "Sydney",
        invitationStatus: false,
        applied: false
    },
    {
        id: 6,
        date: new Date('June 21, 2021'),
        startTime: new Date('June 21, 2021 18:30:00'),
        endTime:new Date('June 21, 2021 19:30:00'),
        type: "Intensive Care General",
        salaryPerHour: 40.25,
        place:"A Nice Hospital",
        rating: 4.5,
        address: "10 Nice Street",
        zipCode: 2000,
        state: "NSW",
        city: "Sydney",
        invitationStatus: false,
        applied: false
    },
    {
        id: 7,
        date: new Date('June 21, 2021'),
        startTime: new Date('June 21, 2021 12:00:00'),
        endTime:new Date('June 21, 2021 16:30:00'),
        type: "Intensive Care General",
        salaryPerHour: 40.25,
        place:"A Nice Hospital",
        rating: 4.5,
        address: "10 Nice Street",
        zipCode: 2000,
        state: "NSW",
        city: "Sydney",
        invitationStatus: false,
        applied: false
    },
    {
        id: 8,
        date: new Date('June 20, 2021'),
        startTime: new Date('June 20, 2021 14:30:00'),
        endTime:new Date('June 20, 2021 16:30:00'),
        type: "Intensive Care General",
        salaryPerHour: 40.25,
        place:"A Nice Hospital",
        rating: 3.5,
        address: "10 Nice Street",
        zipCode: 2000,
        state: "NSW",
        city: "Sydney",
        invitationStatus: false,
        applied: false
    },
    {
        id: 9,
        date: new Date('June 19, 2021'),
        startTime: new Date('June 19, 2021 12:30:00'),
        endTime:new Date('June 19, 2021 16:30:00'),
        type: "Intensive Care General",
        salaryPerHour: 40.25,
        place:"A Nice Hospital",
        rating: 5,
        address: "10 Nice Street",
        zipCode: 2000,
        state: "NSW",
        city: "Sydney",
        invitationStatus: false,
        applied: false
    },
    {
        id: 10,
        date: new Date('June 9, 2021'),
        startTime: new Date('June 9, 2021 10:00:00'),
        endTime:new Date('June 9, 2021 16:00:00'),
        type: "Intensive Care General",
        salaryPerHour: 40.25,
        place:"A Nice Hospital",
        rating: 4.5,
        address: "10 Nice Street",
        zipCode: 2000,
        state: "NSW",
        city: "Sydney",
        invitationStatus: false,
        applied: false
    },
    {
        id: 11,
        date: new Date('June 6, 2021'),
        startTime: new Date('June 6, 2021 16:30:00'),
        endTime:new Date('June 6, 2021 18:30:00'),
        type: "Intensive Care General",
        salaryPerHour: 40.25,
        place:"A Nice Hospital",
        rating: 4.5,
        address: "10 Nice Street",
        zipCode: 2000,
        state: "NSW",
        city: "Sydney",
        invitationStatus: false,
        applied: false
    },
    {
        id: 12,
        date: new Date('June 15, 2021'),
        startTime: new Date('June 15, 2021 10:30:00'),
        endTime:new Date('June 15, 2021 16:00:00'),
        type: "Intensive Care General",
        salaryPerHour: 40.25,
        place:"A Nice Hospital",
        rating: 4.5,
        address: "10 Nice Street",
        zipCode: 2000,
        state: "NSW",
        city: "Sydney",
        invitationStatus: false,
        applied: false
    },
    {
        id: 13,
        date: new Date('June 14, 2021'),
        startTime: new Date('June 14, 2021 16:00:00'),
        endTime:new Date('June 14, 2021 19:00:00'),
        type: "Intensive Care General",
        salaryPerHour: 40.25,
        place:"A Nice Hospital",
        rating: 4.5,
        address: "10 Nice Street",
        zipCode: 2000,
        state: "NSW",
        city: "Sydney",
        invitationStatus: false,
        applied: false
    },
    {
        id: 14,
        date: new Date('June 13, 2021'),
        startTime: new Date('June 24, 2021 19:00:00'),
        endTime:new Date('June 24, 2021 20:00:00'),
        type: "Intensive Care General",
        salaryPerHour: 40.25,
        place:"A Nice Hospital",
        rating: 3.5,
        address: "10 Nice Street",
        zipCode: 2000,
        state: "NSW",
        city: "Sydney",
        invitationStatus: false,
        applied: false
    }


]